import logging
from fastapi import APIRouter, Depends, HTTPException
from database import db_dependency

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/notifications/voice-script")
async def get_voice_script(db=Depends(db_dependency)):
    async with db.execute(
        "SELECT voice_script, updated_at FROM dashboard_cache WHERE id=1"
    ) as c:
        row = await c.fetchone()

    if not row or not row[0]:
        # Generate on demand
        from ai_pipeline import generate_morning_brief
        result = await generate_morning_brief(db)
        return {"voice_script": result.get("voice_script", ""), "generated": True}

    return {"voice_script": row[0], "updated_at": row[1], "generated": False}


@router.get("/notifications/push-summary")
async def get_push_summary(db=Depends(db_dependency)):
    """Return a push notification payload for the most critical thread."""
    async with db.execute("""
        SELECT id, subject, urgency_level, ai_summary, property_name
        FROM threads
        WHERE urgency_score IS NOT NULL
        ORDER BY urgency_score DESC NULLS LAST
        LIMIT 1
    """) as c:
        top = await c.fetchone()

    async with db.execute("""
        SELECT COUNT(*) FROM threads WHERE urgency_level='critical'
    """) as c:
        critical_count = (await c.fetchone())[0]

    async with db.execute("""
        SELECT COUNT(*) FROM threads WHERE urgency_level='high'
    """) as c:
        high_count = (await c.fetchone())[0]

    if not top:
        return {
            "title": "No critical issues",
            "body": "Portfolio is up to date.",
            "urgency": "low",
            "thread_id": None,
        }

    return {
        "title": f"🔴 {critical_count} critical | 🟠 {high_count} urgent",
        "body": (top[3] or top[1] or "")[:120],
        "urgency": top[2],
        "thread_id": top[0],
        "property": top[4],
    }


@router.get("/notifications/email-digest")
async def get_email_digest(db=Depends(db_dependency)):
    """Return HTML email digest of today's priorities."""
    async with db.execute("""
        SELECT id, subject, property_name, urgency_level, ai_summary
        FROM threads
        WHERE urgency_score IS NOT NULL
        ORDER BY urgency_score DESC NULLS LAST
        LIMIT 10
    """) as c:
        threads = [dict(r) for r in await c.fetchall()]

    urgency_colors = {
        "critical": "#ef4444",
        "high": "#f97316",
        "medium": "#eab308",
        "low": "#22c55e",
    }

    rows_html = ""
    for t in threads:
        color = urgency_colors.get(t["urgency_level"] or "low", "#94a3b8")
        rows_html += f"""
        <tr>
          <td style="padding:8px;border-bottom:1px solid #e2e8f0;">
            <span style="background:{color};color:white;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:bold;">
              {(t['urgency_level'] or '').upper()}
            </span>
          </td>
          <td style="padding:8px;border-bottom:1px solid #e2e8f0;font-weight:600;">{t['subject']}</td>
          <td style="padding:8px;border-bottom:1px solid #e2e8f0;color:#64748b;">{t['property_name'] or ''}</td>
          <td style="padding:8px;border-bottom:1px solid #e2e8f0;font-size:13px;color:#475569;">{(t['ai_summary'] or '')[:100]}...</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:'DM Sans',Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px;color:#1e293b;">
  <h2 style="color:#0f172a;border-bottom:2px solid #3b82f6;padding-bottom:8px;">Lette AI — Priority Digest</h2>
  <table style="width:100%;border-collapse:collapse;">
    <thead>
      <tr style="background:#f1f5f9;">
        <th style="padding:8px;text-align:left;">Urgency</th>
        <th style="padding:8px;text-align:left;">Subject</th>
        <th style="padding:8px;text-align:left;">Property</th>
        <th style="padding:8px;text-align:left;">Summary</th>
      </tr>
    </thead>
    <tbody>{rows_html}</tbody>
  </table>
  <p style="color:#94a3b8;font-size:12px;margin-top:20px;">Generated by Lette AI</p>
</body></html>"""

    from fastapi.responses import HTMLResponse
    return HTMLResponse(content=html)
